### ISSUE TITLE
Calls not initiated after cloning

### ISSUE THREAD

**Issue by Fabwelt** [ChainSafe/game-web3wallet#7]
Hi,

I have cloned the web3wallet to: https://fabwelt.github.io/MetamaskConnect/

But when aded the ?action call, nothing is happening: https://fabwelt.github.io/MetamaskConnect/?action=sign&message=Fabwelt%20Arsenal%20DESKTOP%20DEV%201.08

**Comment by sneakzttv** [comment]
@Fabwelt can you invite me to the repo please <3

**Comment by KBryan** [comment]
@Fabwelt I'm not sure exactly what you did. Although, after cloning the repo / running yarn install. Have you tried running this locally first? I have provided a sample setup video.

https://user-images.githubusercontent.com/681817/186036618-ea62bfa4-3306-4636-b51e-ee5eab49c409.mp4

**Comment by Fabwelt** [comment]
I followed the doc. Just cloned the project and point web3wallet file in Unity to the new url.

**Comment by KBryan** [comment]
Can you provide an image in the console? You must be receiving some error.

**Comment by KBryan** [comment]
You will also need to edit the package.json file to conform to the directory where the signer will be found.  I'm assuming this is why it is working locally and not when you deploy to your hosting.

**Comment by Fabwelt** [comment]
I am getting Uncaught SyntaxError: Cannot use import statement outside a module on hosted version

**Comment by Fabwelt** [comment]
Allright, after making the changes to package.json I did a build and uploaded the build to connect.fabwelt.com/arsenal. Now its working

**Comment by Fabwelt** [comment]
https://docs.gaming.chainsafe.io/mobile-and-desktop#hosting-your-own-sign-page this is not simply working. You need to yarn install, make the changes to package.json and then yarn build before uploading public.

**Comment by sneakzttv** [comment]
we'll append this to the docs, it's in the web3wallet repo here but we'll add it
![image](https://user-images.githubusercontent.com/57473220/186246751-e7d6e436-ad2c-4aab-933c-fb3362938418.png)

**Comment by Fabwelt** [comment]
Yes i think it will be more clear to add it to the tutorial. Great work guys! Thanks

**Comment by WoodsFiend** [comment]
I am having this exact same issue but there is no answer in this thread. What was the fix? I have run yarn, yarn start and yarn build. This does not make any changes in the repo or the deployed page.

**Comment by KBryan** [comment]
Here's a video of the process using [GitHub Pages](https://pages.github.com/) 

https://youtu.be/joilum3bcJ8

**Comment by WoodsFiend** [comment]
I think I figured it out with help of your video. Should probably post the steps of what to do with the contents of dist folder once its built. I was doing everything except moving the files from dist to the root of repo.
